refine Appeal.last_hour() to return datetime object
was causing Bid Alert Notification to fail with:
    "AttributeError: 'Alert' object has no attribute 'to_pyhton'"